"""Add users table, rename categories to lists

Revision ID: 0004
Revises: 0003
Create Date: 2025-01-04 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create users table
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("google_id", sa.String(255), nullable=False, unique=True),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("picture", sa.Text, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # Rename categories → lists
    op.rename_table("categories", "lists")

    # Rename column category_id → list_id on tasks
    op.alter_column("tasks", "category_id", new_column_name="list_id")

    # Drop the old foreign key and unique constraint, then re-create them
    # The FK name is auto-generated by SQLAlchemy convention
    op.drop_constraint("tasks_category_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_list_id_fkey", "tasks", "lists", ["list_id"], ["id"], ondelete="SET NULL"
    )

    # Add user_id column to lists
    op.add_column(
        "lists",
        sa.Column(
            "user_id",
            sa.Integer,
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=True,
        ),
    )

    # Drop old unique constraint on name, add (user_id, name) unique
    op.drop_constraint("categories_name_key", "lists", type_="unique")
    op.create_unique_constraint("lists_user_id_name_key", "lists", ["user_id", "name"])


def downgrade() -> None:
    # Remove the composite unique constraint
    op.drop_constraint("lists_user_id_name_key", "lists", type_="unique")

    # Re-add original unique constraint on name
    op.create_unique_constraint("categories_name_key", "lists", ["name"])

    # Remove user_id from lists
    op.drop_column("lists", "user_id")

    # Restore FK
    op.drop_constraint("tasks_list_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_category_id_fkey",
        "tasks",
        "lists",
        ["list_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Rename list_id → category_id
    op.alter_column("tasks", "list_id", new_column_name="category_id")

    # Rename lists → categories
    op.rename_table("lists", "categories")

    # Drop users table
    op.drop_table("users")
